defaults:
  smtp_config: &smtp_config
    smtp_address: smtp.example.com
    smtp_port: 587
    smtp_domain: example.com
    smtp_username: vaccines@example.com
    smtp_password: zD3OGIC7xZ0i
    smtp_from: "\"Vaccine Bot\" <vaccines@example.com>"
  sms_config: &sms_config
    outgoing_phone_number: "+19999999999"
    twilio_account_sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxx
    twilio_auth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  walmart_config: &walmart_config
    cookie: "TODO"

interval_seconds: 20
verbose: true
runners:
  -
    bots:
      -
        class: WalmartBot
        location_id: 1180
        location_name: Billings Bridge
        location_address: 2277 Riverside Drive
        <<: *walmart_config
      -
        class: WalmartBot
        location_id: 1114
        location_name: South Keys
        location_address: 2210 Bank St.
        <<: *walmart_config
      -
        class: ShoppersBot
        latitude: "44.00000000000"
        longitude: "-73.00000000"
        results_per_page: 24
    success_notifiers:
      -
        class: ConsoleNotifier
      -
        class: EmailNotifier
        recipient_email: hello@example.com
        <<: *smtp_config
      -
        class: SMSNotifier
        recipient_phone_number: "+18888888888"
        <<: *sms_config
    error_notifiers:
      -
        class: ConsoleNotifier
      -
        class: EmailNotifier
        recipient_email: hello@example.com
        <<: *smtp_config
