notifiers:
  - EmailNotifier
  - ConsoleNotifier
  - SMSNotifier

bots:
  - WalmartBillingsBot

walmart_bot:
  cookie: "TODO"

interval_seconds: 60

verbose: true

email:
  smtp_address: smtp.example.com
  smtp_port: 587
  smtp_domain: mail.example.com
  smtp_username: ex@mail.example.com
  smtp_password: asdf
  smtp_from: "\"Vaccine Bot\" <vaccines@mail.example.com>"
  email_notifier_recipient: test@example.com

sms:
  outgoing_phone_number: "+19999999999"
  recipient_phone_number: "+18888888888"
  twilio_account_sid: TODO
  twilio_auth_token: TODO
